name: islamicapp_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Janna-LT
      fonts:
       - asset: assets/fonts/Janna-LTRegular.ttf
       - asset: assets/fonts/Janna-LTBold.ttf
         style: normal
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/Suras/
    - assets/json/Hadeth/
    - assets/images/on_boarding/
    - assets/images/azkar/

  
flutter_gen:
  output: lib/gen/
